package com.baseProject.myBaseProject.enums;

public enum AdminAuditAction {
    SUPPORT_ASSIGNED,
    SUPPORT_PRIORITY_CHANGED,
    SUPPORT_STATUS_CHANGED,
    SUPPORT_MESSAGE_ADDED,
    USER_ACCESS_CHANGED,
    USER_SESSIONS_REVOKED,
    USER_VERIFICATION_SENT,
    USER_PASSWORD_RESET_SENT,
    INTERVIEW_PREPARATION_RETRIED,
    INTERVIEW_SCORING_RETRIED,
    INTERVIEW_FORCE_CLOSED,
    INTERVIEW_TERMINATED,
    TEMPLATE_REVIEWED,
    TEMPLATE_METADATA_CHANGED,
    TEMPLATE_PUBLISHED,
    TEMPLATE_UNPUBLISHED,
    ANNOUNCEMENT_CREATED,
    ANNOUNCEMENT_UPDATED,
    ANNOUNCEMENT_SCHEDULED,
    ANNOUNCEMENT_CANCELLED,
    SYSTEM_SETTING_CHANGED,
    BACKGROUND_JOB_TRIGGERED,
    STORAGE_DELETION_RETRIED,
    ACCOUNT_DELETION_RETRIED
}
