package com.baseProject.myBaseProject.enums;

public enum UserNotificationType {
    CV_READY,
    CV_FAILED,
    JOB_DESCRIPTION_READY,
    JOB_DESCRIPTION_FAILED,
    INTERVIEW_REPORT_READY,
    INTERVIEW_REPORT_FAILED,
    SUPPORT_TICKET_UPDATED,
    TEMPLATE_APPROVED,
    TEMPLATE_REJECTED,
    TEMPLATE_HIDDEN,
    ADMIN_ANNOUNCEMENT
}
