package com.baseProject.myBaseProject.exception;

import com.baseProject.myBaseProject.constant.Message;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    // Interview templates
    TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, Message.TEMPLATE_NOT_FOUND),
    TEMPLATE_VERSION_CONFLICT(HttpStatus.CONFLICT, Message.TEMPLATE_VERSION_CONFLICT),
    TEMPLATE_ARCHIVED(HttpStatus.CONFLICT, Message.TEMPLATE_ARCHIVED),
    TEMPLATE_INVALID_ANALYSIS(HttpStatus.UNPROCESSABLE_CONTENT, Message.TEMPLATE_INVALID_ANALYSIS),
    TEMPLATE_INSUFFICIENT_JD(HttpStatus.UNPROCESSABLE_CONTENT, Message.TEMPLATE_INSUFFICIENT_JD),
    TEMPLATE_ALREADY_CONFIRMED(HttpStatus.CONFLICT, Message.TEMPLATE_ALREADY_CONFIRMED),
    TEMPLATE_CONFIRM_REQUIRED(HttpStatus.CONFLICT, Message.TEMPLATE_CONFIRM_REQUIRED),
    TEMPLATE_REVIEW_NOT_ALLOWED(HttpStatus.CONFLICT, Message.TEMPLATE_REVIEW_NOT_ALLOWED),
    TEMPLATE_APPROVAL_REQUIRED(HttpStatus.CONFLICT, Message.TEMPLATE_APPROVAL_REQUIRED),

    // Interview sessions
    INTERVIEW_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, Message.INTERVIEW_SESSION_NOT_FOUND),
    INTERVIEW_SESSION_OPTION_INVALID(HttpStatus.BAD_REQUEST, Message.INTERVIEW_SESSION_OPTION_INVALID),
    INTERVIEW_SESSION_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_IDEMPOTENCY_CONFLICT),
    INTERVIEW_SESSION_PREPARATION_NOT_RETRYABLE(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_PREPARATION_NOT_RETRYABLE),
    INTERVIEW_SESSION_PREPARATION_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, Message.INTERVIEW_SESSION_PREPARATION_FAILED),
    INTERVIEW_PLAN_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, Message.INTERVIEW_PLAN_INVALID),
    INTERVIEW_REPLY_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, Message.INTERVIEW_REPLY_INVALID),
    INTERVIEW_ASSESSMENT_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, Message.INTERVIEW_ASSESSMENT_INVALID),
    INTERVIEW_SCORING_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, Message.INTERVIEW_SCORING_FAILED),
    INTERVIEW_SCORING_NOT_RETRYABLE(HttpStatus.CONFLICT, Message.INTERVIEW_SCORING_NOT_RETRYABLE),
    INTERVIEW_REPORT_NOT_AVAILABLE(HttpStatus.CONFLICT, Message.INTERVIEW_REPORT_NOT_AVAILABLE),
    INTERVIEW_SESSION_NOT_STARTABLE(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_NOT_STARTABLE),
    INTERVIEW_SESSION_NOT_IN_PROGRESS(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_NOT_IN_PROGRESS),
    INTERVIEW_SESSION_MODE_MISMATCH(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_MODE_MISMATCH),
    INTERVIEW_TURN_OUT_OF_SEQUENCE(HttpStatus.CONFLICT, Message.INTERVIEW_TURN_OUT_OF_SEQUENCE),
    INTERVIEW_TURN_IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT, Message.INTERVIEW_TURN_IDEMPOTENCY_CONFLICT),
    INTERVIEW_TURN_PROCESSING(HttpStatus.CONFLICT, Message.INTERVIEW_TURN_PROCESSING),
    INTERVIEW_TURN_NOT_RETRYABLE(HttpStatus.CONFLICT, Message.INTERVIEW_TURN_NOT_RETRYABLE),
    INTERVIEW_SESSION_NOT_CANCELLABLE(HttpStatus.CONFLICT, Message.INTERVIEW_SESSION_NOT_CANCELLABLE),
    INTERVIEW_ADMIN_OPERATION_INVALID(HttpStatus.CONFLICT, Message.INTERVIEW_ADMIN_OPERATION_INVALID),
    PROFILE_CONFIRM_REQUIRED(HttpStatus.CONFLICT, Message.PROFILE_CONFIRM_REQUIRED),

    // Speech
    SPEECH_NOT_ENABLED(HttpStatus.SERVICE_UNAVAILABLE, Message.SPEECH_NOT_ENABLED),
    SPEECH_CONFIG_ERROR(HttpStatus.SERVICE_UNAVAILABLE, Message.SPEECH_CONFIG_ERROR),
    SPEECH_INVALID_AUDIO(HttpStatus.BAD_REQUEST, Message.SPEECH_INVALID_AUDIO),
    SPEECH_AUDIO_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE, Message.SPEECH_AUDIO_TOO_LARGE),
    SPEECH_PROVIDER_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, Message.SPEECH_PROVIDER_UNAVAILABLE),
    SPEECH_PROVIDER_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, Message.SPEECH_PROVIDER_TIMEOUT),
    SPEECH_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY, Message.SPEECH_PROVIDER_ERROR),
    SPEECH_TRANSCRIPTION_FAILED(HttpStatus.BAD_GATEWAY, Message.SPEECH_TRANSCRIPTION_FAILED),
    SPEECH_SYNTHESIS_FAILED(HttpStatus.BAD_GATEWAY, Message.SPEECH_SYNTHESIS_FAILED),
    SPEECH_TURN_NOT_SYNTHESIZABLE(HttpStatus.CONFLICT, Message.SPEECH_TURN_NOT_SYNTHESIZABLE),

    // Realtime interview
    REALTIME_CONFIG_ERROR(HttpStatus.SERVICE_UNAVAILABLE, Message.REALTIME_CONFIG_ERROR),
    REALTIME_NOT_ENABLED(HttpStatus.SERVICE_UNAVAILABLE, Message.REALTIME_NOT_ENABLED),
    REALTIME_SESSION_NOT_AVAILABLE(HttpStatus.CONFLICT, Message.REALTIME_SESSION_NOT_AVAILABLE),
    REALTIME_VOICE_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, Message.REALTIME_VOICE_NOT_SUPPORTED),
    REALTIME_PROVIDER_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, Message.REALTIME_PROVIDER_UNAVAILABLE),
    REALTIME_PROVIDER_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, Message.REALTIME_PROVIDER_TIMEOUT),
    REALTIME_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY, Message.REALTIME_PROVIDER_ERROR),
    REALTIME_CONNECTION_NOT_FOUND(HttpStatus.NOT_FOUND, Message.REALTIME_CONNECTION_NOT_FOUND),
    REALTIME_EVENT_INVALID(HttpStatus.BAD_REQUEST, Message.REALTIME_EVENT_INVALID),
    REALTIME_EVENT_SEQUENCE_CONFLICT(HttpStatus.CONFLICT, Message.REALTIME_EVENT_SEQUENCE_CONFLICT),
    REALTIME_RESUMPTION_NOT_AVAILABLE(HttpStatus.CONFLICT, Message.REALTIME_RESUMPTION_NOT_AVAILABLE),

    // Job descriptions
    JD_FILE_REQUIRED(HttpStatus.BAD_REQUEST, Message.JD_FILE_REQUIRED),
    JD_INVALID_FILE_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, Message.JD_INVALID_FILE_TYPE),
    JD_FILE_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE, Message.JD_FILE_TOO_LARGE),
    JD_FILE_CORRUPTED(HttpStatus.BAD_REQUEST, Message.JD_FILE_CORRUPTED),
    JD_TOO_MANY_PAGES(HttpStatus.BAD_REQUEST, Message.JD_TOO_MANY_PAGES),
    JD_TEXT_TOO_LONG(HttpStatus.CONTENT_TOO_LARGE, Message.JD_TEXT_TOO_LONG),
    JD_EMPTY_TEXT(HttpStatus.UNPROCESSABLE_CONTENT, Message.JD_EMPTY_TEXT),
    JD_LIMIT_REACHED(HttpStatus.CONFLICT, Message.JD_LIMIT_REACHED),
    JD_NOT_FOUND(HttpStatus.NOT_FOUND, Message.JD_NOT_FOUND),
    JD_PROCESSING_IN_PROGRESS(HttpStatus.CONFLICT, Message.JD_PROCESSING_IN_PROGRESS),
    JD_PROCESSING_NOT_RETRYABLE(HttpStatus.CONFLICT, Message.JD_PROCESSING_NOT_RETRYABLE),
    JD_FILE_NOT_AVAILABLE(HttpStatus.CONFLICT, Message.JD_FILE_NOT_AVAILABLE),
    JD_PROCESSING_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, Message.JD_PROCESSING_FAILED),
    JD_ANALYSIS_NOT_READY(HttpStatus.CONFLICT, Message.JD_ANALYSIS_NOT_READY),

    // ---- 404 ----
    ENDPOINT_NOT_FOUND(HttpStatus.NOT_FOUND, Message.ENDPOINT_NOT_FOUND),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "Resource not found"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, Message.USER_NOT_FOUND),

    // ---- 409 ----
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, "Email already registered"),
    DATA_CONSTRAINT_VIOLATION(HttpStatus.CONFLICT, Message.CONSTRAINT_VIOLATION),
    ADMIN_USER_STATUS_PROTECTED(HttpStatus.CONFLICT, Message.ADMIN_USER_STATUS_PROTECTED),

    // ---- 400 ----
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST, Message.VALIDATION_FAILED),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST, Message.MALFORMED_JSON),

    // ---- 401 / 403 ----
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, Message.INVALID_CREDENTIALS),
    AUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, Message.AUTHENTICATION_REQUIRED),
    ACCOUNT_DISABLED(HttpStatus.UNAUTHORIZED, Message.ACCOUNT_DISABLED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, Message.ACCESS_DENIED),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "Invalid or expired refresh token"),
    MISSING_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, Message.MISSING_REFRESH_TOKEN),
    INVALID_GOOGLE_TOKEN(HttpStatus.UNAUTHORIZED, Message.INVALID_GOOGLE_TOKEN),
    CURRENT_PASSWORD_INVALID(HttpStatus.UNAUTHORIZED, Message.CURRENT_PASSWORD_INVALID),

    // Account lifecycle
    ACCOUNT_TOKEN_INVALID(HttpStatus.BAD_REQUEST, Message.ACCOUNT_TOKEN_INVALID),
    EMAIL_ALREADY_VERIFIED(HttpStatus.CONFLICT, Message.EMAIL_ALREADY_VERIFIED),
    PASSWORD_NOT_CONFIGURED(HttpStatus.CONFLICT, Message.PASSWORD_NOT_CONFIGURED),
    DEVICE_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, Message.DEVICE_SESSION_NOT_FOUND),
    ACCOUNT_DELETION_NOT_PENDING(HttpStatus.CONFLICT, Message.ACCOUNT_DELETION_NOT_PENDING),
    ACCOUNT_DELETION_ADMIN_FORBIDDEN(HttpStatus.FORBIDDEN, Message.ACCOUNT_DELETION_ADMIN_FORBIDDEN),

    // ---- 405 / 500 / 503 ----
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED, "Method not allowed"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, Message.INTERNAL_ERROR),
    GOOGLE_LOGIN_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE, Message.GOOGLE_LOGIN_NOT_CONFIGURED),

    // ---- AI / CV ----
    AI_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, Message.AI_SERVICE_UNAVAILABLE),
    AI_TIMEOUT(HttpStatus.GATEWAY_TIMEOUT, Message.AI_TIMEOUT),
    AI_MALFORMED_OUTPUT(HttpStatus.INTERNAL_SERVER_ERROR, Message.AI_MALFORMED_OUTPUT),
    AI_CONFIG_ERROR(HttpStatus.SERVICE_UNAVAILABLE, Message.AI_CONFIG_ERROR),
    AI_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, Message.AI_ERROR),
    CV_PARSE_FAILED(HttpStatus.UNPROCESSABLE_CONTENT, Message.CV_PARSE_FAILED),

    // ---- CV upload ----
    UPLOAD_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE, Message.UPLOAD_TOO_LARGE),
    CV_FILE_REQUIRED(HttpStatus.BAD_REQUEST, Message.CV_FILE_REQUIRED),
    CV_INVALID_FILE_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, Message.CV_INVALID_FILE_TYPE),
    CV_FILE_TOO_LARGE(HttpStatus.CONTENT_TOO_LARGE, Message.CV_FILE_TOO_LARGE),
    CV_FILE_CORRUPTED(HttpStatus.BAD_REQUEST, Message.CV_FILE_CORRUPTED),
    CV_TOO_MANY_PAGES(HttpStatus.BAD_REQUEST, Message.CV_TOO_MANY_PAGES),
    CV_LIMIT_REACHED(HttpStatus.CONFLICT, Message.CV_LIMIT_REACHED),
    CV_NOT_FOUND(HttpStatus.NOT_FOUND, Message.CV_NOT_FOUND),
    CV_PARSE_IN_PROGRESS(HttpStatus.CONFLICT, Message.CV_PARSE_IN_PROGRESS),
    CV_PARSE_NOT_RETRYABLE(HttpStatus.CONFLICT, Message.CV_PARSE_NOT_RETRYABLE),
    STORAGE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, Message.STORAGE_UNAVAILABLE),

    // ---- Candidate profile ----
    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, Message.PROFILE_NOT_FOUND),
    PROFILE_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, Message.PROFILE_ITEM_NOT_FOUND),
    DUPLICATE_SKILL_NAME(HttpStatus.CONFLICT, Message.DUPLICATE_SKILL_NAME),
    PROFILE_VERSION_CONFLICT(HttpStatus.CONFLICT, Message.PROFILE_VERSION_CONFLICT),

    // ---- Notifications ----
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, Message.NOTIFICATION_NOT_FOUND),

    // ---- User feedback and support ----
    INTERVIEW_FEEDBACK_NOT_FOUND(HttpStatus.NOT_FOUND, Message.INTERVIEW_FEEDBACK_NOT_FOUND),
    INTERVIEW_FEEDBACK_NOT_AVAILABLE(HttpStatus.CONFLICT, Message.INTERVIEW_FEEDBACK_NOT_AVAILABLE),
    SUPPORT_TICKET_NOT_FOUND(HttpStatus.NOT_FOUND, Message.SUPPORT_TICKET_NOT_FOUND),
    SUPPORT_TICKET_CONTEXT_INVALID(HttpStatus.BAD_REQUEST, Message.SUPPORT_TICKET_CONTEXT_INVALID),
    SUPPORT_TICKET_TRANSITION_INVALID(HttpStatus.CONFLICT, Message.SUPPORT_TICKET_TRANSITION_INVALID),
    SUPPORT_TICKET_CLOSED(HttpStatus.CONFLICT, Message.SUPPORT_TICKET_CLOSED),
    SUPPORT_ASSIGNEE_INVALID(HttpStatus.BAD_REQUEST, Message.SUPPORT_ASSIGNEE_INVALID),

    // Announcements
    ANNOUNCEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, Message.ANNOUNCEMENT_NOT_FOUND),
    ANNOUNCEMENT_STATE_INVALID(HttpStatus.CONFLICT, Message.ANNOUNCEMENT_STATE_INVALID),
    ANNOUNCEMENT_VERSION_CONFLICT(HttpStatus.CONFLICT, Message.ANNOUNCEMENT_VERSION_CONFLICT);

    private final HttpStatus status;
    private final String defaultMessage;
}
